name: ChestAnyWhere
version: 1.0.0 
main: co.andrescol.mc.plugin.chestanywhere
description: With this plugin you can save items in a SQLite or MySQL Database for each player
author: [xX_andrescol_Xx]
api-version: 1.19
commands:
  sopen: 
    description: Open the storage 
    permission-message: '[Storage] You dont haver permission for this command'
    permission: storage.open.other
    usage: Incorrect usage, try /sopen <reload|player>
permissions: 
  storage.sopen: {description: Allow to open other players storage, default: op}
  storage.reloadconfig: {description: Allow to reload the configuration, default: op}
      
    