name: ChestAnyWhere
version: 1.0.0 
main: co.andrescol.mc.plugin.chestanywhere.ChestAnyWherePlugin
description: With this plugin you can save items in a SQLite or MySQL Database for each player
author: xX_andrescol_Xx
api-version: 1.19
commands:
  copen:
    description: Open the storage 
    permission-message: '[ChestAnyWhere] You dont haver permission for this command'
    permission: chestanywhere.cmd
    usage: Incorrect usage, try /copen [reload|player]
permissions: 
  chestanywhere.cmd: {description: Allow to open other players storage, default: op}
  chestanywhere.cmd.reload: {description: Allow to reload the configuration, default: op}
  chestanywhere.inventory.size.9: { description: Allow to open other players storage, default: op }